spring.application.name=spave

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:ZmFrZS10ZXN0LXNlY3JldC1rZXktZm9yLWxvY2FsLWFuZC1jaS1vbmx5LW5vdC1wcm9k}


spring.mail.host=smtp.zohocloud.ca
spring.mail.port=465
spring.mail.username=contact@spaveapp.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.ssl.enable=true
